[package]
name = "desktop-ui-foundation"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.3"
env_logger = "0.11.3"
crossbeam-channel = "0.5.15"
cpal = "0.16.0"
fundsp = "0.20.0"
miniquad = "0.4.8"
glam = "0.30.5"
midir = "0.10.2"
ringbuf = "0.4.8"
