[package]
name = "prototype-001"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.3"
cpal = "0.16.0"
fundsp = "0.20.0"
midir = "0.10.2"
crossbeam-channel = "0.5.15"
triple_buffer = "8.1.1"
miniquad = "0.4.8"
